CREATE PROCEDURE uspPedidoActualizar
@id varchar(36),
@fechaPedido varchar(10),
@tipoComprobante int,
@tipoPago int,
@subTotal numeric(10,2),
@subTotalEnvase numeric(10,2),
@total numeric(10,2),
@direccion varchar(1000),
@referencia varchar(1000),
@latitud varchar(20),
@longitud varchar(20),
@observacion varchar(1000),
@idUbigeo varchar(36),
@idZonalVenta varchar(36),
@nombre varchar(500),
@correo varchar(200),
@tipoDocumento int,
@numeroDocumento varchar(20),
@telefono varchar(20),
@movil varchar(20),
@nombreCP varchar(500),
@tipoDocumentoCP int,
@numeroDocumentoCP varchar(20),
@direccionCP varchar(1000),
@estado int,
@usuario varchar(500)

AS

update Pedido SET
	FechaPedido = CONVERT(date,@fechaPedido,103),
	TipoComprobante = @tipoComprobante,
	TipoPago = @tipoPago,
	Subtotal = @subTotal,
	SubtotalEnvase = @subTotalEnvase,
	Total = @total,
	Direccion = @direccion,
	Referencia = @referencia,
	Latitud = @latitud,
	Longitud = @longitud,
	Observacion = @observacion,
	IdUbigeo = @idUbigeo,
	IdZonalVenta = @idZonalVenta,
	Nombre = @nombre,
	Correo = @correo,
	TipoDocumento = @tipoDocumento,
	NumeroDocumento = @numeroDocumento,
	Telefono = @telefono,
	Movil = @movil,
	NombreCP = @nombreCP,
	TipoDocumentoCP = @tipoDocumentoCP,
	NumeroDocumentoCP = @numeroDocumentoCP,
	DireccionCP = @direccionCP,
	Estado = @estado,
	UsuarioEdicion = @usuario,
	FechaEdicion = GETDATE()
where CONVERT(varchar(36),IdPedido) = @id